# Application properties config for DEVELOPMENT environment

dma:
  allowed-origins: '*'
logging:
  level:
    web: 'debug'
server:
  address: '0.0.0.0'
spring:
  devtools:
    add-properties: true
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/dmadb'
    username: 'user'
    password: 'password'
  h2:
    console:
      enabled: false
  jpa:
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    properties:
      hibernate:
        format_sql: true
    show-sql: true
