# Application properties config for PRODUCTION environment

dma:
  allowed-origins: 'https://www.dndmapp.nl.eu.org/'
logging:
  level:
    web: 'warn'
spring:
  devtools:
    add-properties: false
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    database-platform: 'org.hibernate.dialect.MariaDB103Dialect'
    hibernate:
      ddl-auto: 'validate'
    open-in-view: false
  sql:
    init:
      mode: 'never'
