# This workflow will run tests, create a Docker image,
# and releases it to the GitHub Container Registry.

name: release
on:
    release:
        types: [published]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    TARGET_PLATFORMS: linux/arm/v7

jobs:
  test:
    uses: nonamer777/dma-server/.github/workflows/test.yml@master
  release-and-build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout the repository
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            id: docker_buildx
            uses: docker/setup-buildx-action@v1

          - name: Cache Docker layers
            uses: actions/cache@v2
            with:
                path: /tmp/.docker-buildx-cache
                key: ${{ runner.os }}-docker-buildx-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-docker-buildx-

          - name: Login to Dockerhub
            uses: docker/login-action@v1
            with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Extract metadata for Docker
            id: meta
            uses: docker/metadata-action@v3
            with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
                builder: ${{ steps.buildx.outputs.name }}
                cache-from: type=local,src=/tmp/.docker-buildx-cache
                cache-to: type=local,dest=/tmp/.docker-buildx-cache-new
                context: ./
                file: ./Dockerfile
                labels: ${{ steps.meta.outputs.labels }}
                platforms: ${{ env.TARGET_PLATFORMS }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
          - name: Move cache
            run: |
                rm -rf /tmp/.docker-buildx-cache
                mv /tmp/.docker-buildx-cache-new /tmp/.docker-buildx-cache

          - name: Digest image
            run: echo ${{ steps.docker_build.outputs.digest }}
