# This workflow will run tests.

name: test
on:
    workflow_call:
        secrets:
            token:
                required: false
    pull_request:
        branches:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  java-version: 11
                  distribution: 'adopt'
            - name: Run tests with Gradle
              run: |
                  ./gradlew test
